version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "type: dependencies"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/"
    labels:
      - "type: dependencies"
    target-branch: dev
    schedule:
      interval: "daily"
