name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  # What's Changed
  $CHANGES
categories:
  - title: "Breaking"
    label: "breaking"
  - title: "New"
    label: "feature"
  - title: "Bug Fixes"
    label: "bug"
  - title: "Testing"
    label: "tests"
  - title: "Maintenance"
    label: "maintenance"
  - title: "Documentation"
    label: "documentation"
  - title: "Dependency Updates"
    label: "dependencies"

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "bug"
      - "maintenance"
      - "documentation"
      - "dependencies"
      - "security"
      - "patch"
      - "tests"