name: action ci - firefox

on:
  push:
  pull_request:

# This ensures that previous jobs for the workflow are canceled when the ref is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [latest, latest-devedition, latest-beta, latest-esr, '84.0' ]
        os: [ubuntu, windows, macos]
        exclude:
          - os: macos
            version: latest-devedition
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build files
        run: yarn build
      - name: Package action
        run: yarn package

      - name: Install firefox ${{ matrix.version }}
        uses: ./
        id: browser
        with:
          browser: firefox
          version: ${{ matrix.version }}
      - if: runner.os != 'Windows'
        run: ${{ steps.browser.outputs.binary }} --version
      - if: runner.os == 'Windows'
        run: (Get-Item (Get-Command "${{ steps.browser.outputs.path }}\${{ steps.browser.outputs.binary }}").Source).VersionInfo.ProductVersion
