name: action ci - chrome

on:
  push:
  pull_request:

# This ensures that previous jobs for the workflow are canceled when the ref is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [latest, dev, beta, stable, 1000000]
        os: [ubuntu, macos, windows]
        exclude:
          - os: macos
            version: 1000000
          - os: windows
            version: 1000000
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build files
        run: yarn build
      - name: Package action
        run: yarn package

      - name: Install chrome ${{ matrix.version }}
        id: browser
        uses: ./
        with:
          browser: chrome
          version: ${{ matrix.version }}
      - if: runner.os != 'Windows'
        run: ${{ steps.browser.outputs.binary }} --version
      - if: runner.os == 'Windows'
        run: (Get-Item (Get-Command ${{ steps.browser.outputs.binary }}).Source).VersionInfo.ProductVersion
