name: Codeowners

on:
  pull_request:
    paths-ignore:
      - '**/CODEOWNERS'
    branches:
      - main

# This ensures that previous jobs for the workflow are canceled when the ref is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    # only apply on unmerged pull requests
    if: github.event.pull_request.merged_by == ''
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4
        with:
          # the fetch depth 0 (=all) is important
          fetch-depth: 0
      - name: update code owners
        uses: gofunky/update-codeowners@v0.3.1
        with:
          distribution: 25
          token: ${{ secrets.CODEOWNER_TOKEN }}

      - name: check file
        run: cat .github/CODEOWNERS

      - name: Commit and push
        uses: test-room-7/action-update-file@v1.4.0
        with:
          commit-msg: "Updated CHANGELOG.md"
          file-path: ".github/CODEOWNERS"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev