name: Generate action docs
on:
  push:
    paths:
      - action.yml

# This ensures that previous jobs for the workflow are canceled when the ref is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README.md from action.yml
        uses: Dirrk/action-docs@v1