name: Release CI

on:
  release:
    types: [published]
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z]+[0-9]+)?
    branches:
      - main

# This ensures that previous jobs for the workflow are canceled when the ref is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    name: "Release Drafter"
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}